In [74]:
import numpy as np
from numpy.linalg import inv

##### Polynomial Regression from Scratch

In [75]:
#Generate x values
x = np.array([float(i) for i in range(1, 11)])
#format x values to N x M matrix (allows for multinomial vectors later)
x = x[:, np.newaxis]
x

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [76]:
#Generate (errorless) target variables
y = np.array([(i**2 + 2*i) for i in x])
print(y)

[[  3.]
 [  8.]
 [ 15.]
 [ 24.]
 [ 35.]
 [ 48.]
 [ 63.]
 [ 80.]
 [ 99.]
 [120.]]


In [77]:
#number of records
rows = x.shape[0]

#degree of polynomial you want
degrees = 3

#create a blank n x m+1 design matrix (the +1 allows for the y-intercept constant)
dmatrix = np.zeros((rows, (degrees+1)))
#print(dmatrix)

for i in range(degrees+1):
    #raise each column to power of i
    dmatrix[:,i] = x[:,0]**i

A = dmatrix
print(A)

[[   1.    1.    1.    1.]
 [   1.    2.    4.    8.]
 [   1.    3.    9.   27.]
 [   1.    4.   16.   64.]
 [   1.    5.   25.  125.]
 [   1.    6.   36.  216.]
 [   1.    7.   49.  343.]
 [   1.    8.   64.  512.]
 [   1.    9.   81.  729.]
 [   1.   10.  100. 1000.]]


In [78]:
#This step is not necessary (just makes it read L-R like the original polynomial that made y)
#Flip the matrix horizontally so it reads like a normal expression with highest powers fist
A = np.flip(A, 1)
A

array([[   1.,    1.,    1.,    1.],
       [   8.,    4.,    2.,    1.],
       [  27.,    9.,    3.,    1.],
       [  64.,   16.,    4.,    1.],
       [ 125.,   25.,    5.,    1.],
       [ 216.,   36.,    6.,    1.],
       [ 343.,   49.,    7.,    1.],
       [ 512.,   64.,    8.,    1.],
       [ 729.,   81.,    9.,    1.],
       [1000.,  100.,   10.,    1.]])

In [79]:
# if you uncomment here and try to invert it errors because it is not invertible
# invA = inv(A)
# invA

In [80]:
#To solve this multiply both sides by transpose A 
At = A.transpose()
print(At)

#Take product of AT & A to "square the matrix" so it can be inversed
A_sq = np.dot(At, A)
print(A_sq)

#must perform the operation on both sides of the equation
y_sq = np.dot(At, y)
print(y_sq)

[[   1.    8.   27.   64.  125.  216.  343.  512.  729. 1000.]
 [   1.    4.    9.   16.   25.   36.   49.   64.   81.  100.]
 [   1.    2.    3.    4.    5.    6.    7.    8.    9.   10.]
 [   1.    1.    1.    1.    1.    1.    1.    1.    1.    1.]]
[[1.978405e+06 2.208250e+05 2.533300e+04 3.025000e+03]
 [2.208250e+05 2.533300e+04 3.025000e+03 3.850000e+02]
 [2.533300e+04 3.025000e+03 3.850000e+02 5.500000e+01]
 [3.025000e+03 3.850000e+02 5.500000e+01 1.000000e+01]]
[[271491.]
 [ 31383.]
 [  3795.]
 [   495.]]


In [81]:
# Now you can solver for x  (i.e. find the missing coefficients)
# rearrange as follows .. A*x=b  =>  x=b/A  =>  x = A^-1 * b


coefficients = np.dot(inv(A_sq), y_sq)
print(coefficients)

[[ 8.52651283e-14]
 [ 1.00000000e+00]
 [ 2.00000000e+00]
 [-7.27595761e-12]]


In [82]:
#some of these coefficents are tiny fractions. 
# If we display them rounded it is more obvious what the result is

print(np.round_(coefficients.transpose(), decimals=2))

[[ 0.  1.  2. -0.]]


In [83]:
#so the resuling equations is  ...

#  0x^3 + 1x^2  + 2x  +  0

#Which is exactly what we started with